CREATE TABLE PRODUTOS (
    CODIGO        INT         NOT NULL ,
    DESCRICAO     VARCHAR(50) NOT NULL ,
    DATA_VALIDADE DATETIME,
    EAN           VARCHAR(15) NOT NULL,
    IND_INATIVO   INT         NOT NULL DEFAULT 0
)
;
GO
ALTER TABLE    PRODUTOS 
ADD CONSTRAINT PK_PRODUTOS
PRIMARY KEY   (CODIGO)
;
GO
CREATE INDEX IDX_PRODUTOS_EAN
ON PRODUTOS (EAN)
;
GO
INSERT INTO PRODUTOS VALUES (1, 'Nome do Protudo', GETDATE(), '1234567890', 0);
